#!/bin/bash
TARGET="/public"
GIT_DIR="/private/REPO_NAME.git"
TARGET_BRANCH="BRANCH_NAME"

while read oldrev newrev ref
do
    BRANCH=$(git rev-parse --symbolic --abbrev-ref $ref)

    if [[ $BRANCH == $TARGET_BRANCH ]];
    then
        echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f
    else
        echo "Ref $ref received. Doing nothing: only the ${TARGET_BRANCH} branch may be deployed on this server."
    fi
done
